In [8]:
import numpy as np
import pandas as pd

In [14]:
data = pd.read_csv('play_tennis.csv')
data.head()
data.drop(columns = ['day'], inplace=True)

In [15]:
data

     outlook  temp humidity    wind play
0      Sunny   Hot     High    Weak   No
1      Sunny   Hot     High  Strong   No
2   Overcast   Hot     High    Weak  Yes
3       Rain  Mild     High    Weak  Yes
4       Rain  Cool   Normal    Weak  Yes
5       Rain  Cool   Normal  Strong   No
6   Overcast  Cool   Normal  Strong  Yes
7      Sunny  Mild     High    Weak   No
8      Sunny  Cool   Normal    Weak  Yes
9       Rain  Mild   Normal    Weak  Yes
10     Sunny  Mild   Normal  Strong  Yes
11  Overcast  Mild     High  Strong  Yes
12  Overcast   Hot   Normal    Weak  Yes
13      Rain  Mild     High  Strong   No

In [2]:
#problem 1
# outlook = sunny, temp=Hot, Humidity = High, Wind = Weak
# play or no play?

In [4]:
# solution
# p(yes | sunny, hot, high, weak) = p(sunny|yes) * p(hot|yes) * p(high|yes) * p(weak |yes) * p(yes)
# p(no | sunny, hot, high, weak) = p(sunny |no) *p(hot|no) *p(high|no)* p(weak|no) *p(no)

# compare and decide using maximum a postirori rule

In [5]:
# problem 2

# in the training stage, naive bayes creates a lookup table (which it will store in a dictionary)
# the algorithm will explore the dataset in the training phase

In [6]:
# p(yes)
# p(no)

In [10]:
data['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [11]:
py = 9/14 # p(yes)
pn = 5/14 # p(no)

In [12]:
# now lets create a lookup table!!

# working on the outlook column
pd.crosstab(data['outlook'],data['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [13]:
Pon = 0 / 5 # probability for overcast for no
Prn = 2/ 5 # probability for rain for no
Psn = 3/5. # probability for sunny for no

Poy = 4/9  # probability for overcast for yes
Pry = 3/9 # probability for rain for yes
Psy = 2/9 # probability for sunny for yes

In [16]:
# creating the same for the next column i.e temp
pd.crosstab(data['temp'],data['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [17]:
Pcn = 1/5 # cool for no
Phn = 2/5 # hot for no
Pmn = 2/5 # mild for no

Pcy = 3/9 # cool for yes
Phy = 2/9 # hot for yes
Pmy = 4/9 # mild for yes

In [18]:
# creating the same for humidity
pd.crosstab(data['humidity'],data['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [19]:
PHn = 4/5
Pnn = 1/5

PHy = 3/9
pny = 6/9

In [20]:
# creating the same for wind
pd.crosstab(data['wind'],data['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [21]:
psn = 3/5
pwn = 2/5

psy = 3/9
pwy = 6/9

In [24]:
# p(yes | sunny, hot, high, weak)
pyes = py * Psy * Phy * PHy * pwy
pyes

0.007054673721340388

In [26]:
# p(no | sunny, hot, high, weak)
pnos = pn * Psn * Phn * PHn * pwn
pnos

0.02742857142857143

In [ ]:
# no play!!